---
repos:
  - repo: local
    hooks:
      - id: go test
        name: go test
        entry: go test -race ./...
        language: system
        always_run: false
        verbose: false
        pass_filenames: false
        stages:
          - commit
        types:
          - go
fail_fast: true
