name: Go

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Fetch all tags
      run: git fetch --force --tags

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check formatting
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          exit 1;
        fi

    - name: Test
      run: go test -race -v ./...

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

